# Welcome to Jekyll! (Header par défaut)

# Main Page Setup
title: Trovalet Denis - Portfolio Chimie Verte

# Hero Section
name: Trovalet Denis
headline: Étudiant en Master Chimie Verte - Synthèse Durable & Catalyse
description: >-
  Étudiant en Master Chimie Verte à l'Université de Strasbourg (2025-2026). Passionné par les approches durables en synthèse organique, catalyse (homo/hétérogène) et valorisation de la biomasse. Expérience en TP de synthèse et détermination structurale. À la recherche d'un stage en R&D pour appliquer mes compétences en chimie verte à des projets industriels innovants. Maîtrise de l'anglais et du français pour des collaborations internationales.

# Profile Image - Remplace le placeholder !
profile_image: ./assets/images/profile-image/avatar.jpeg  # Upload ta photo pro ici (ex. toi en labo, 300x300px JPEG)

# Resume Link
resume-url: /assets/resume/cv-chimie-verte.pdf  # Upload ton CV PDF dans /assets/resume/

# External Links (ajoute les tiens)
external-links:
  linkedin:  # Ex. : "trovalet-denis"
  github: ouilascience  # Ton username GitHub

# Skills - Structure YAML pour grille stylée
skills:
  - category: Chimie Fondamentale
    tools:
    - Chimie Organique (synthèse et stratégies vertes)
    - Chimie Inorganique et de Coordination
    - Chimie Organométallique
    - Chimie Supramoléculaire
  - category: Catalyse & Synthèse Durable
    tools:
    - Catalyse Homogène et Hétérogène
    - Biocatalyse et Organocatalyse
    - Valorisation de la Biomasse
    - Approches Vertes en Synthèse Organique
  - category: Analyse & Évaluation Environnementale
    tools:
    - Analyse de Cycle de Vie (ACV)
    - Évaluation des Impacts Environnementaux
    - Droit de l'Environnement
    - Spectroscopies pour Détermination Structurale
  - category: Outils Expérimentaux
    tools:
    - TP de Synthèse et Chimie Physique
    - Projet Interdisciplinaire en Durabilité (PID)
    - Normes et Réglementations Chimiques

# Contact Form
formspree-key:  # Ajoute ta clé si tu as un formulaire

# Thème - Force le mint pour couleurs vertes/éco ; fallback basic si bug
colors:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"

# Build settings (ne change pas)
collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects
